global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "goscry"
    metrics_path: /metrics
    static_configs:
      - targets: ["goscry:8080"]
    scrape_interval: 5s
    scrape_timeout: 4s

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
